### PR TITLE
Edit attachments

### PR DESCRIPTION
**Pull request by clbn**
1. Add ability to remove attachments on create-post.
2. Add ability to add/remove attachments on edit-post (on a single-post page only, not on a timeline page).

2015-09-30 18-51-53 pepyatka-edit-diff

### CODE REVIEW

**Comment by urbansheep** [comment]
Update is awesome, guys!

**Comment by urbansheep** [comment]
Green/red marking is not ok with color blindness.
I'd rather mark images with large cross/overlay over the image and text labels so that things are clear.

frf-edit-attch

Cross is × — &times;
Yellow color for tags/outline is #ffb915 (standard yellow from “like” hearts), border is 4px.

**Comment by clbn** [comment]
@urbansheep Thanks for your feeedback!
1. Have you seen the interface live? I'd suggest to put it on Peppa (after I address two Berkus' comments above), so you and testers could click around and play with it and see what's going on with overlays on mouseover etc. Just for all of us to be on the same page before tweaking it.
2. On your suggestions: looks nice, I like it, but I have a couple of "but"s:

2.1. If we are going to have yellow border thicker than 2px, we'll have jumping line of image, since it's going to be bigger than others. 

2.2. What about non-image attachments?

**Comment by clbn** [comment]
Another rant (I can't help it), now about official colors: we have #f9cb16 for yellow and #ef4a23 for red. These are from the big throbber and I use them everywhere.

(Alternative, used in ico: #f9b616 for yellow and #d43e1b for red. I would not consider these "canon".)

**Comment by clbn** [comment]
I've addressed comments about renaming button from "Save" to "Update" and moving them consistently to the right. Also, there's a notice on attachments when editing post on timeline page.

@berkus @indeyets @epicmonkey Ping.

**Pull request merged**
