### PR TITLE
Fix throbber on transition between pages...

### PR DESCRIPTION
**Pull request by clbn**
... and on reloading page with logo-click.

THE THROBBER STRIKES BACK.

(I changed some indentation as well, feel free to object, I surely can revert it.)

### CODE REVIEW

**Comment by epicmonkey** [comment]
LGBT

**Comment by epicmonkey** [comment]
LGTM

**Comment by clbn** [comment]
rainbow-8

**Comment by berkus** [comment]
Pull-request ReactiveCocoa-style!

**Comment by berkus** [comment]
I worship his Shadow!

**Pull request merged**
