### PR TITLE
#comment-<id> for using as URL hash

### PR DESCRIPTION
**Pull request by clbn**

### CODE REVIEW

**Comment by clbn** [comment]
You can test it here: https://frf.applied.creagenics.com/clbn2/43e69628-fc48-44c8-998f-bc3ff78aab9d#comment-ccaada35-8404-41d4-ae32-0fec39c6f9fc

**Comment by berkus** [comment]
Same for beta frontend pls?

**Comment by clbn** [comment]
@berkus Yeah, it's just I don't really know yet how to make scrolling-after-render work there.

Oh you're quick-merger, I would like to hear @urbansheep's opinion on the chosen format (`#comment-` vs. `#c-` vs. `#weirdstuff-` etc.)

**Comment by berkus** [comment]
`#comment-id` is good

**Pull request merged**
