### PR TITLE
Scroll to the top of the post on collapsing attachments

### LINKED ISSUE #514: [Verified] Scroll up to the post when collapsing expanded pictures
Right now when photos are collapsed view remains scrolled to the place where collapse button appeared. This is a bit annoying as you then need to manually scroll back to where you were reading your feed.

Pre-condition: post with more than 5 pictures in your feed.
1. Log in.
2. Scroll to the post from pre-conditions.
3. Click Expand.
4. Scroll down.
5. Click Collapse.

Expected: I'm seeing the same post as if I'd never expanded the pictures.
Actual: I'm scrolled way down :(

### PR DESCRIPTION
**Pull request by clbn**
Fixes #514.

<s>It really makes sense to do it in both cases: expanding and collapsing.</s>
Collapsing is enough for now.

### CODE REVIEW

**Comment by indeyets** [comment]
hm… not sure about this. expansion is:
1. always pushing content down, leaving scroll-position intact
2. deliberate (following user's click)

so, why do we need compensation here?

**Comment by clbn** [comment]
@indeyets On expanding we want to see all the pictures, right? So scrolling down to the post's top help us focus on the post's pictures and give us more room on the screen for them immediately.

**Comment by clbn** [comment]
TRUST ME,
I'M AN ENGINEER

**Comment by indeyets** [comment]
got it. we should get more opinions on this one. I'm not convinced.

**Comment by clbn** [comment]
Sure, let's listen to other people's arguments.

**Comment by urbansheep** [comment]
My .02:

0) Smooth scroll FTW.
1) If expansion adds something to the flow then first object of this something should scroll into view.
2) If things get collapsed, and top edge of the _image container_ is visible/in view, then everything should stay intact, no repositioning required.
3) If top edge of the _image container_ is out of view, then after collapsing we should scroll to make this image container visible completely.

**Comment by epicmonkey** [comment]
@urbansheep could you talk a little about 1) and 3) please?

**Comment by clbn** [comment]
I've updated scrolling (now it's smooth). Check it out: http://frf.creagenics.com:3333/clbn6

**Comment by indeyets** [comment]
same as with another scroll-issue: doesn't work in my Firefox-41 :-/

**Comment by berkus** [comment]
Scrolls smoothly in safari to picture block start on unfold and fold back.

**Comment by urbansheep** [comment]
@epicmonkey
1) Expansion means explicit “show me more” request. If reader views the image set and it is at the bottom of the screen (especially on smaller screens/mobile), then when reader taps/clicks the toggle, she might not see the added content, and has to scroll down manually (one extra tap/swipe). If browser scrolls down a little when expanding image set, reader clearly sees added content without extra actions/overhead.

2) Collapsing means “show me less (but don't mess up with what I am looking at)”, so if we don't scroll up on collapsing, we might suddenly drop reader in the middle of the comment thread and/or other posts, disrupting expectations and position if there were a lot of images under the fold.

**Comment by clbn** [comment]
(@indeyets Just updated it with a fix for Firefox.)

**Comment by clbn** [comment]
For your convenience, I've added a couple of long image sets to that testing link.

**Comment by epicmonkey** [comment]
Like it.

PS. there is a slight delay when you collapse images and app scrolls you back.

**Comment by clbn** [comment]
@epicmonkey I can see it twitching in Firefox, is it what you are using? I have an idea why it happens there, need to check.

**Comment by epicmonkey** [comment]
I see delay here: http://frf.creagenics.com:3333/clbn6/b635e391-c087-4f45-bfa8-ddd435bc26df.
- collapse images
- (images collapsed instantly)
- browser scrolls me up in ~0.25s

**Comment by clbn** [comment]
Ah, yeah. Maybe images have to collapse smoothly as well.

**Comment by berkus** [comment]
indeyets [10:18 AM]
не-не… ты не понял. я другой пост читаю :wink:
на экран влезает 4-5 постов, например, читаю верхний, а картинки развернул у нижнего

berkus [10:21 AM]
я вижу тут простую проверку - если текущая позиция верха поста во вьюпорте. то ничего скроллить не надо

@clbn we need to add this as a hotfix.

**Comment by clbn** [comment]
@berkus @epicmonkey @indeyets @urbansheep 
I've updated it, guys. Not all of your comments were addressed, but still there are two changes:
1. Now it's only triggered on collapsing.
2. There is a check if top of the post is within the viewport.

Feel free to test it on http://frf.creagenics.com:3333/clbn6

**Pull request merged**
