### PR TITLE
Add 10px margin to the header

### PR DESCRIPTION
**Pull request by cmarat**
Aligns the page title ("Freefeed") with other elements on the page.

### CODE REVIEW

**Comment by clbn** [comment]
This would break it for small screens (now it's aligned on mobile etc).

I believe it should be fixed with some `col-md-*` juggling, instead of breaking the grid.

**Comment by cmarat** [comment]
You are right, the box-header-timeline and box-body have extra margin/padding only on wider screens. It's taken into account in b0d61cea803c0be664ca019353e479aff316daa5

**Comment by clbn** [comment]
Good! Let's move it to the top of @media selector (line 24), to maintain the same order as in previous @media block.

After that, let's squash the commits and we're golden.

**Comment by cmarat** [comment]
Done.

**Comment by clbn** [comment]
:+1:

**Pull request merged**
