### PR TITLE
Change player style.

### PR DESCRIPTION
**Pull request by berkus**

### CODE REVIEW

**Comment by epicmonkey** [comment]
Shouldn't it be in the freefeed repo?

**Comment by berkus** [comment]
If you're intending to keep standard black player for pepyatka then sure.

**Comment by epicmonkey** [comment]
Who knows... I'd say it makes sense to separate brandings and keep pepyatka as generic as possible.

**Comment by berkus** [comment]
Ok, lets keep styling separately.

**Pull request closed without merging**
