### PR TITLE
fix for hanging comma in likes usernames list

### PR DESCRIPTION
**Pull request by innin**
mixed css+templates solution instead of css-only

### CODE REVIEW

**Comment by indeyets** [comment]
@innin can we get rid of css magic completely?

**Comment by n1313** [comment]
Yes, of course. You need to check against loop index, insert comma after each of the elements except the last one, and insert "and" after the one before the last. http://stackoverflow.com/questions/21841340/what-is-the-correct-way-of-getting-the-index-of-an-array-when-iterating-over-it

**Comment by innin** [comment]
@indeyets yes, hold this, I will try to find solution. @n1313 yes, there are many discussions on that but pure handlebars syntax does not work here, Ember has custom #each helper implementation

**Comment by innin** [comment]
@indeyets updated. Still had to add helpers to Handlebars, because it does not support dynamic expressions as `{{#if}}` arguments

**Pull request merged**
