### PR TITLE
Enabled HTML5 History API in EmberJS app

### PR DESCRIPTION
**Pull request by indeyets**
Implementation is trivial, copy-pasted from documentation and just works™

### CODE REVIEW

**Comment by innin** [comment]
Looks like nginx config needs to be updated as well. Links will work if you start from / entry point, but refreshing page or visiting some url directly will give 404 an error. I use nginx.conf from Ansible

**Comment by indeyets** [comment]
right. I tested against plain express-server

**Comment by epicmonkey** [comment]
summon @id

**Comment by innin** [comment]
```
try_files $uri $uri/ /index.html?/$request_uri;
```
at / location works

**Comment by id** [comment]
Looking into it.

**Comment by id** [comment]
https://github.com/pepyatka/pepyatka-ansible/pull/22

**Comment by id** [comment]
This one and https://github.com/pepyatka/pepyatka-ansible/pull/22 preferably should be merged ~ at the same time.

**Pull request merged**
