### PR TITLE
Transition to real home after sub/unsub

### PR DESCRIPTION
**Pull request by kappa**
Should stay at the same page while refreshing status but it will require much more work.

See #112.

### CODE REVIEW

**Comment by epicmonkey** [comment]
I'm thinking we can just drop this `transitionTo` and so user will stay on the same page. However we'll have to change object state to "subscribed". Pushing this a little further we'll need to extract subscribe/unsubscribe methods to model and that way we can do following in the controller
```
var user = this.get('model.user')
user.subscribe() // <- will send AJAX request and push user to subscribed list
  .then(function() {} ) // <- do nothing here
```

**Comment by epicmonkey** [comment]
I thought that Post#like and Post#unlike could be examples how to do this, but those methods only send AJAX request and do not change object state at all. :ambulance:

**Comment by kappa** [comment]
Right now, removing transitionTo() altogether leaves the user with no visible reaction to her clicks at all. Once subscription status and subs counters are updated (via pubsub server events?), transitionTo() may be removed.

**Comment by epicmonkey** [comment]
Counters will be updated automatically when we receive right response from the server, e.g. user record and status message (now server just returns an empty json `{}`) and update user record in Ember. Though it is a bit more to do, it's not a big refactoring.

**Pull request closed without merging**
