### PR TITLE
Game of Fonts

### PR DESCRIPTION
**Pull request by clbn**
Game of Fonts
- Increase font-size for post's .info (datetime, actions, likes)

Game of Icons
- Align icons for likes and comments according to bigger font-size

### CODE REVIEW

**Comment by clbn** [comment]
Sorry guys. OCD.

**Comment by berkus** [comment]
Got scrreenshot before->after?

**Comment by clbn** [comment]
Do you want to publish it or something? I can get some tomorrow.

**Comment by berkus** [comment]
Just want to compare the visual difference before merging.

**Comment by clbn** [comment]
I think you'll need `screenshotcomparison.com` for comparing them. :grin: 

2015-09-19 02-35-32 game-of-fonts-1

2015-09-19 02-37-33 game-of-fonts-2

**Pull request merged**
