### PR TITLE
Update autosize lib (3.0.5 -> 3.0.14)

### PR DESCRIPTION
**Pull request by clbn**

### CODE REVIEW

**Comment by berkus** [comment]
But i've already updated it here https://github.com/FreeFeed/freefeed-html/commit/65cc06d75c25504c2e32acbf55a061304fd5addf

**Comment by clbn** [comment]
Well, who knew. It was not in `pepyatka-html` and not in the prod website.

**Comment by clbn** [comment]
(Anyway, it's unlikely it solves the problem, but worth trying.)

**Comment by berkus** [comment]
Applied in `freefeed-html`.

**Pull request closed without merging**
